clientId: 13368
clientSecret: J0Jf6olSEVNcXln9
groupId: 61f3bc61-e2f3-36fd-9327-53146195c74f
filename_csv:  output/fer_library_csv.csv
filename_csv_sorted: output/fer_library_csv_sorted.csv
filename_html: output/fer_library_html.html
filename_redirect_html: redirect.html
